// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabSFll6IEZsjXHyvxVbkU5yOgGrkP56g',
    appId: '1:652246955746:web:00449f4c5011b5974210bb',
    messagingSenderId: '652246955746',
    projectId: 'vetmobileapp-eeda0',
    authDomain: 'vetmobileapp-eeda0.firebaseapp.com',
    storageBucket: 'vetmobileapp-eeda0.firebasestorage.app',
    measurementId: 'G-7P3BLYR6TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXYDmo_Pfg0lHSyzENqPCBeHoSNoW9tE',
    appId: '1:652246955746:android:08783029b30e7f5b4210bb',
    messagingSenderId: '652246955746',
    projectId: 'vetmobileapp-eeda0',
    storageBucket: 'vetmobileapp-eeda0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQpSJUEnOu77hTk7-PMT8qYNOhktH7p9A',
    appId: '1:652246955746:ios:1e3d9dc25f92373b4210bb',
    messagingSenderId: '652246955746',
    projectId: 'vetmobileapp-eeda0',
    storageBucket: 'vetmobileapp-eeda0.firebasestorage.app',
    iosBundleId: 'com.example.vetMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQpSJUEnOu77hTk7-PMT8qYNOhktH7p9A',
    appId: '1:652246955746:ios:1e3d9dc25f92373b4210bb',
    messagingSenderId: '652246955746',
    projectId: 'vetmobileapp-eeda0',
    storageBucket: 'vetmobileapp-eeda0.firebasestorage.app',
    iosBundleId: 'com.example.vetMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabSFll6IEZsjXHyvxVbkU5yOgGrkP56g',
    appId: '1:652246955746:web:e9250147675206304210bb',
    messagingSenderId: '652246955746',
    projectId: 'vetmobileapp-eeda0',
    authDomain: 'vetmobileapp-eeda0.firebaseapp.com',
    storageBucket: 'vetmobileapp-eeda0.firebasestorage.app',
    measurementId: 'G-PJ7H50ZH58',
  );
}
